kind: ConfigMap 
apiVersion: v1 
metadata:
  name: example-configmap 
data:
  # variables de entorno
  database: mongodb
  database_uri: mongodb://localhost:27017

---

kind: Pod 
apiVersion: v1 
metadata:
  name: pod-env-var 
spec:
  containers:
    - name: env-var-configmap
      image: nginx:1.7.9 
      envFrom:
        - configMapRef:
            name: example-configmap